### ISSUE TITLE
Build fails...

### ISSUE THREAD

**Issue by fusionfoto** [phantomxdev/phantomx#1]
Probably for a similar issue to this. Tried on RPI:

https://github.com/EmberCoin/Ember/issues/31

bignum.h: In function ‘bool operator<=(const CBigNum&, const CBigNum&)’:
bignum.h:717:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 rator<=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) <= 0); }
                                                                    ^
bignum.h: In function ‘bool operator>=(const CBigNum&, const CBigNum&)’:
bignum.h:718:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 rator>=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) >= 0); }
                                                                    ^
bignum.h: In function ‘bool operator<(const CBigNum&, const CBigNum&)’:
bignum.h:719:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 erator<(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) < 0); }
                                                                     ^
bignum.h: In function ‘bool operator>(const CBigNum&, const CBigNum&)’:
bignum.h:720:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 erator>(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) > 0); }
                                                                     ^
makefile.unix:217: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1

running, low and behold, SSL 1.1:

ii  libssl-dev:armhf                       1.1.0f-3+deb9u1                    armhf        Secure Sockets Layer toolkit - development files
i

For anyone trying to build this with up to date libraries, it'll fail.

**Comment by fusionfoto** [comment]
Apparently bitcoin fixed it in this issue:

https://github.com/bitcoin/bitcoin/issues/7086

so the changes just need to be ported.

**Comment by alexml83** [comment]
The problem is for the version of openssl.... you just have to change to older version...

**Comment by fusionfoto** [comment]
I get that, but obviously that is not a long term plan... We can't all be using private, old repositories of old SSL... particularly when there are security fixed in the new versions.

**Comment by phantomx-beta** [comment]
Problems solved on updated Readme.md and autoinstall file

* Bignum errors ocurred when not have enought Ram -> Need to create a swap file
* SSL repositorie need to bee changed to jessie one on RPI
