### ISSUE TITLE
MNs stopped working. 

### ISSUE THREAD

**Issue by fusionfoto** [phantomxdev/phantomx#2]
Something weird just happened to my MNs.  Up until a few hours ago, they were working.

The hash, for example --

shows up correctly in the block explorer:

http://78.109.28.154:3001/tx/4ed1826d604145e6a68531a49060d5cdb0a1c061e9bb5447b0b866d4b6cca890

However, in my phantomx wallet... shows up as TWO transactions of

http://www.imagecoast.com/images/miner/phantomxscrewiness.jpg

So, unsurprisingly my wallet shows no masternode outputs.

Again, working masternodes, nothing changes, boom, wallet thinks its two transactions, even though the block explorer agrees. I'm going to blow away the local block chain and see if that helps.

Also, tried upgrading to the latest phantomx wallet -- no help there.

Tried setting staking=0 and reservebalance=99999 in the conf file. No luck there. Locking my wallet stops the staking, but I can't try to start an MN that way. As soon as I try, its staking and fails anyway. When I set reservebalance true 99999 in the console, staking stops, but no collateral is accepted for the MN.

Please help so I can get my MNs working again. They were working and suddenly stopped exactly at the same moment my SWIPP one did.

**Comment by fusionfoto** [comment]
Separately, the MN immediately closes any connection via telnet to the phantomx port... even though its receiving payments, I'd ideally like to actually do MN work for those payments.

**Comment by phantomx-beta** [comment]
Does it continue happening on v 1.3.0 version? did you tried to reindex the wallet? What OS are you using?
